name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version number  (eg 1.0.0)'
        required: true
jobs:
  createrelease:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install bumpversion
      run: pip3 install bumpversion
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.versionName }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Update Changelog
      uses: thomaseizinger/keep-a-changelog-new-release@1.2.1
      with:
        version: ${{ github.event.inputs.versionName }}
    - name: Commit changelog, project and docker-compose files
      id: make-commit
      run: |
        bumpversion --allow-dirty --verbose --new-version ${{ github.event.inputs.versionName }} patch
        echo "::set-output name=commit::$(git rev-parse HEAD)"
    - name: Push new branch
      run: git push --tags origin release/v${{ github.event.inputs.versionName }}
    - name: Create pull request into main
      uses: thomaseizinger/create-pull-request@1.2.1
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       head: release/v${{ github.event.inputs.versionName }}
       base: master
       title: v${{ github.event.inputs.versionName }} into main
       reviewers: ${{ github.event.issue.user.login }}
       body: |
           Hi!
           This PR was created in response workflow running.
           I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.

